config/routes.rb
Rails.application.routes.draw do
  

  get 'users/index'

  devise_for :users
  get 'home/dashboard'
  get 'static_pages/home'
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :role
	before_create :set_default_role
	before_validation :set_default_role 

	private
	def set_default_role
		self.role ||= Role.find_by_name('user')
	end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	
	layout :layout_by_resource

	private
	def layout_by_resource
		if devise_controller?
			"devise"
		else
			"application"
		end
	end

	def after_sign_in_path_for(resource)
		home_dashboard_url
	end

	def after_sign_out_path_for(resource)
		root_url
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
	def dashboard
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  def index
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/dashboard.html.erb
<h1>Home#dashboard</h1>
<p>Find me in app/views/home/dashboard.html.erb</p>

<%= link_to "Sign out", destroy_user_session_url %>
<%= link_to "show_index_of_users", users_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zone Website</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zone Website - Devise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<% if user_signed_in? %>
	<%= link_to "Sign out", destroy_user_session_url %>
<% else %>
	<%= link_to "Sign in", new_user_session_url %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.email %>
  <%= user.role.name %>
<% end %>